import { writeFileSync } from "fs"
import { join } from "path"
import { fetchCityAndCinemasData } from "../src/dynamic-cinemas"

(async () => {
  try {
    const data = await fetchCityAndCinemasData()
    // const file = join(__dirname, "..", "data", "cinemas.json")
    // writeFileSync(file, JSON.stringify(data, null, 2))

    const tsFile = join(__dirname, "..", "src", "cinemas.ts")
    writeFileSync(tsFile, `// WARNING!! This file is automatically generated on build time!\n// check scripts directory and package.json scripts for more info\nimport { CinesaCityData } from "./types"\n\nexport const cinemas: CinesaCityData = ${JSON.stringify(data, null, 2)}\n`)
  } catch (error) {
    console.error("error on generating cinemas info", error)
    process.exit(1)
  }
})()
