// WARNING!! This file is automatically generated on build time!
// check scripts directory and package.json scripts for more info
import { CinesaCityData } from "./types"

export const cinemas: CinesaCityData = {
  "a coruña": [
    {
      "name": "Marineda City iSense",
      "id": 1047,
      "cityId": 3130
    }
  ],
  "barcelona": [
    {
      "name": "Barnasud Cinesa LUXE",
      "id": 1037,
      "cityId": 8000
    },
    {
      "name": "Diagonal",
      "id": 120,
      "cityId": 8000
    },
    {
      "name": "Diagonal Mar iSense IMAX®",
      "id": 232,
      "cityId": 8000
    },
    {
      "name": "SOM Multiespai",
      "id": 291,
      "cityId": 8000
    },
    {
      "name": "La Farga Cinesa LUXE",
      "id": 113,
      "cityId": 8000
    },
    {
      "name": "La Maquinista Salas LUXE D-BOX Dolby",
      "id": 661,
      "cityId": 8000
    },
    {
      "name": "Mataró Parc",
      "id": 275,
      "cityId": 8000
    },
    {
      "name": "Parc Vallès iSense",
      "id": 231,
      "cityId": 8000
    }
  ],
  "vizcaya": [
    {
      "name": "Max Ocio",
      "id": 1056,
      "cityId": 48000
    },
    {
      "name": "Zubiarte",
      "id": 1055,
      "cityId": 48000
    }
  ],
  "castellón de la p.": [
    {
      "name": "Salera",
      "id": 1300,
      "cityId": 46000
    }
  ],
  "guipúzcoa": [
    {
      "name": "Urbil",
      "id": 1310,
      "cityId": 50011
    },
    {
      "name": "Garbera Cinesa LUXE",
      "id": 1600,
      "cityId": 20170
    }
  ],
  "las palmas de g. c.": [
    {
      "name": "El Muelle",
      "id": 761,
      "cityId": 35008
    }
  ],
  "madrid": [
    {
      "name": "Capitol",
      "id": 1027,
      "cityId": 28000
    },
    {
      "name": "Equinoccio Madrid Cinesa LUXE iSense ScreenX",
      "id": 631,
      "cityId": 28000
    },
    {
      "name": "Heron City-Las Rozas IMAX®",
      "id": 236,
      "cityId": 28000
    },
    {
      "name": "La Gavia",
      "id": 1039,
      "cityId": 28000
    },
    {
      "name": "La Moraleja Cinesa LUXE D-BOX",
      "id": 601,
      "cityId": 28000
    },
    {
      "name": "Las Rosas",
      "id": 196,
      "cityId": 28000
    },
    {
      "name": "Plaza Loranca 2 Cinesa LUXE",
      "id": 192,
      "cityId": 28000
    },
    {
      "name": "Parquesur IMAX®",
      "id": 190,
      "cityId": 28000
    },
    {
      "name": "Principe Pío iSense",
      "id": 781,
      "cityId": 28000
    },
    {
      "name": "Proyecciones",
      "id": 331,
      "cityId": 28000
    },
    {
      "name": "Manoteras",
      "id": 1052,
      "cityId": 28000
    },
    {
      "name": "Méndez Alvaro iSense",
      "id": 1050,
      "cityId": 28000
    },
    {
      "name": "Nassica iSense ScreenX",
      "id": 1051,
      "cityId": 28000
    },
    {
      "name": "Intu Xanadú Cinesa LUXE iSense",
      "id": 311,
      "cityId": 28000
    },
    {
      "name": "Oasiz Cinesa LUXE iSense D-BOX",
      "id": 2000,
      "cityId": 28000
    }
  ],
  "malaga": [
    {
      "name": "La Cañada",
      "id": 280,
      "cityId": 29600
    }
  ],
  "marratxí - mallorca": [
    {
      "name": "Festival Park IMAX®",
      "id": 234,
      "cityId": 7011
    }
  ],
  "murcia": [
    {
      "name": "Nueva Condomina",
      "id": 1033,
      "cityId": 30000
    }
  ],
  "oviedo": [
    {
      "name": "Parque Principado",
      "id": 701,
      "cityId": 33429
    }
  ],
  "santander": [
    {
      "name": "Bahia de Santander",
      "id": 270,
      "cityId": 39000
    }
  ],
  "santiago de c.": [
    {
      "name": "As Cancelas iSense",
      "id": 1200,
      "cityId": 15703
    }
  ],
  "sevilla": [
    {
      "name": "Camas",
      "id": 1400,
      "cityId": 41001
    }
  ],
  "valencia": [
    {
      "name": "Bonaire Cinesa LUXE iSense ScreenX",
      "id": 721,
      "cityId": 46000
    }
  ],
  "zaragoza": [
    {
      "name": "Grancasa",
      "id": 611,
      "cityId": 50011
    },
    {
      "name": "Puerto Venecia iSense",
      "id": 1100,
      "cityId": 50011
    }
  ]
}
